### ISSUE TITLE
Adicionar link para URL pública

### ISSUE THREAD

**Issue by jbochi** [gBritz/HeroisDoCancer#2]
Por favor!

**Comment by uiliamge** [comment]
Ok,
http://heroisdocancer.apphb.com/

Mas vamos apresentar na máquina local, por problemas de publicação.

2015-04-12 11:57 GMT-03:00 Juarez Bochi notifications@github.com:

> Por favor!
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/gBritz/HeroisDoCancer/issues/2.

## 

_Uiliam Goltz Elesbão_
_Acadêmico de Sistemas de Informação_
http://br.linkedin.com/pub/uiliam-elesb%C3%A3o/20/81a/191

**Comment by uiliamge** [comment]
http://heroisdocancer.apphb.com/

**Comment by jbochi** [comment]
Boa! Obrigado
